"""Regenerate notebooks/train_ropg_kd.ipynb from src/rl/ropg_kd.py.

The notebook must stay self-contained (it runs on Kaggle/Colab with no repo clone),
but hand-mirroring the trainer is what let lr, max_seq_length and best_metric drift
apart from configs/train_ropg.yaml. So the worker cell is generated as a *verbatim*
copy of the module, with only its `personalization.profiles` import inlined. Re-run
this script after any change to src/rl/ropg_kd.py.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULE = (ROOT / "src" / "rl" / "ropg_kd.py").read_text(encoding="utf-8")
PROFILES = (ROOT / "src" / "personalization" / "profiles.py").read_text(encoding="utf-8")
CONFIG = (ROOT / "configs" / "train_ropg.yaml").read_text(encoding="utf-8")

# Inline the profiles import: on Kaggle there is no `personalization` package.
profiles_body = PROFILES.split('"""', 2)[2].lstrip("\n")
profiles_body = profiles_body.replace("from __future__ import annotations\n\n", "")
worker = MODULE.replace(
    "from personalization.profiles import render_profile",
    "# --- inlined from src/personalization/profiles.py (no repo install on Kaggle) ---\n"
    + profiles_body.rstrip()
    + "\n# --- end inlined profiles ---",
)
assert "personalization.profiles" not in worker, "profiles import not inlined"

# derive_triplets is deliberately NOT inlined. The trainer validates the triplet files and
# refuses to run on stale ones; it never rebuilds them, because rebuilding here cannot know
# the label filters (those live in configs/datagen_ropg.yaml) and would silently produce an
# unfiltered run. If this assert fires, a re-derive path crept back into the trainer and the
# `data` package it needs does not exist on Kaggle.
assert "import data.gen_ropg_data" not in worker, (
    "the trainer must not import derive_triplets — derivation belongs to "
    "gen_ropg_data.py --derive-only"
)
assert "from data.gen_ropg_data import" not in worker, (
    "the trainer must not import derive_triplets — derivation belongs to "
    "gen_ropg_data.py --derive-only"
)

# torchrun is the only multi-GPU launcher; catch a reintroduced in-process spawn.
assert "mp.spawn" not in worker, "mp.spawn is gone from the launcher — do not reintroduce"
assert "torch.multiprocessing" not in worker, "torch.multiprocessing import reintroduced"

# The worker is written to a .py file and run by torchrun, so a syntax or indentation error
# introduced by the inlining above surfaces only after the GPUs are already allocated.
# Compiling it here turns that into a build-time failure. (This is exactly how a stray
# indent shipped once: a hard-coded-indent str.replace matched the tail of a deeper-indented
# line and left its leftover spaces glued to the next one.)
compile(worker, "ropg_kd_worker.py", "exec")


def md(text):
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def code(text):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


cells = [
    md("""# ROPG-KD Retriever Training

Stage 1 of Simurgh's two-stage training: LoRA fine-tuning of the Qwen3-Embedding-0.6B
encoder, distilling the offline LLM-judge teacher scores in `data/ropg_kd/{train,val}.jsonl`
(see `notebooks/gen_ropg_data.ipynb`). Checkpoints are selected on validation **Recall@K
over the full corpus, reported per persona** — not on KD loss.

The trainer cell below is a **verbatim copy of `src/rl/ropg_kd.py`**, generated by
`notebooks/build_train_ropg_kd.py`. Do not hand-edit it: change `src/rl/ropg_kd.py` and
regenerate, or the two will drift the way they did before.

**Multi-GPU.** The launch cell uses `torchrun`, which starts one independent OS process
per GPU. Two consequences shape the cells below:
1. torchrun executes a **script path**, so the trainer is written to `ropg_kd_worker.py`
   by the `%%writefile` cell, and `CFG` is dumped to YAML — a fresh interpreter cannot
   receive a Python dict.
2. A fresh interpreter cannot be handed a live Python dict, so `CFG` is written out as
   YAML and passed with `--config`. That also leaves each run reproducible from an
   artifact rather than from notebook state.

**Kaggle setup**
1. Enable GPU accelerator (T4 x2 for DDP; T4 x1 also works).
2. Enable internet access (the encoder is downloaded from Hugging Face).
3. Attach the `simurgh-data` dataset, **version 2+** (must contain `ropg_kd/` and `chunks/corpus.jsonl`).
4. No API secrets needed - training makes no LLM calls.

**`hard_neg` mode needs pre-derived triplets.** The trainer *validates* them and refuses to
start otherwise; it never rebuilds them, because rebuilding here cannot know the label
filters (those live in `configs/datagen_ropg.yaml`) and would silently give you an
unfiltered run under a config that says filtered. So `ropg_kd/` must ship
`{train,val}_triplets.jsonl` (or `_pairs.jsonl`) **and** `train_triplets_meta.json`, built
with `max_negatives` at least as large as `CFG["training"]["max_negatives"]`. Rebuild them
locally — no API calls, no model load, a few seconds:

```bash
uv run python -m data.gen_ropg_data --config configs/datagen_ropg.yaml --derive-only
```

Each run logs the build it trained on (`Triplets: max_negatives=8 | filters=False | groups 1296/1296 retained`), which is how an unfiltered arm is confirmed after the fact.

**Colab setup**
1. Set `RUNTIME = "colab"` in the Config cell.
2. Upload `simurgh-data/` to Drive at `MyDrive/simurgh-data/` with `ropg_kd/{train,val}.jsonl`,
   the derived triplet files above, and `chunks/corpus.jsonl`.
3. Enable GPU accelerator. Checkpoints save straight to Drive, so the zip cell is skipped.
"""),
    code("""!pip install -q -U transformers accelerate peft

# peft's LoRA injection probes every dispatcher, including torchao, for every target
# module. Kaggle's image ships torchao 0.10.0 and recent peft rejects anything below
# 0.16.0 with an ImportError rather than skipping it - so adapter creation dies even
# though nothing here is quantized. Removing the package makes peft's find_spec check
# return False cleanly; upgrading it instead would pull torchao's own torch pin and
# risk replacing Kaggle's CUDA-matched torch build.
!pip uninstall -y -q torchao"""),
    md("## Config\n\nMirrors `configs/train_ropg.yaml`; the last cell warns if the two disagree."),
    code("""import os

# Must be set before torch initializes CUDA; mitigates fragmentation OOMs by letting
# the allocator grow segments instead of hunting for contiguous blocks.
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

from pathlib import Path

# -- Runtime selector ---------------------------------------------------------
RUNTIME = "kaggle"  # "kaggle" | "colab" | "local"
ARM = "ropg_kd"  # "ropg_kd" (filters off) | "ropg_kd_filtered" (filters on)
GDRIVE_BASE = "/content/drive/MyDrive/simurgh-data"  # Colab only

if RUNTIME == "kaggle":
    DATA_ROOT = "/kaggle/input/datasets/alirezahsn/simurgh-data"
    OUTPUT_DIR = "/kaggle/working/ropg_kd_checkpoints"
    WORKDIR = "/kaggle/working"
elif RUNTIME == "colab":
    from google.colab import drive

    drive.mount("/content/drive")
    DATA_ROOT = GDRIVE_BASE
    OUTPUT_DIR = f"{GDRIVE_BASE}/ropg_kd_checkpoints"
    WORKDIR = "/content"
else:  # local
    DATA_ROOT = "data"
    OUTPUT_DIR = "data/rl/ropg_kd_checkpoints"
    WORKDIR = "."

# -- Inline config (mirrors configs/train_ropg.yaml) ---------------------------
CFG = {
    "seed": 42,
    # reader_kd is retained as a documented ablation, not the primary arm: its teacher is
    # a single-sample LLM-judge rating (per-label reliability ~0.17) and listwise KL
    # weights the graded middle of the ranking, where adjacent teacher gaps (0.02-0.03)
    # sit below that noise floor. MNRL reads only the rank-1 vs tail contrast (gap 0.711).
    "mode": "hard_neg",    # hard_neg | reader_kd
    "format": "triplets",  # only used when mode=hard_neg
    "data": {
        # Which derived triplet set to train on - see docs/experiment-design.md,
        # "Stage-1 retriever runs". Both directories are built from the *same* judged
        # {train,val}.jsonl and differ only in whether the label filters ran:
        #   ARM = "ropg_kd"           filters OFF  (runs A, B)
        #   ARM = "ropg_kd_filtered"  filters ON   (runs C, D)
        # This path is exempt from the drift check at the end of the notebook (local and
        # Kaggle roots legitimately differ), so it will NOT warn if you forget to switch
        # it. The per-run "Triplets: ... filters=..." line in the training log is the
        # check that actually catches a wrong arm.
        "train_data": f"{DATA_ROOT}/{ARM}",
        "corpus_path": f"{DATA_ROOT}/chunks/corpus.jsonl",
    },
    "embedder": {
        "model": "Qwen/Qwen3-Embedding-0.6B",
        # Must match the length used when the FAISS index is built, or the same chunk
        # gets two different embeddings at train and serve time. At 2048 the p95 corpus
        # chunk fits whole; only the longest few still truncate.
        "max_seq_length": 2048,
    },
    "training": {
        "device": "cuda",
        "precision": "fp16",   # T4 has no bf16; use bf16 only on A100+
        # Not a tunable on a 16 GB T4: without it one batch_size:1 step retains ~36 GB
        # of activations, with it ~2.5 GB (only each block's input is stored). No
        # batch_size/doc_micro_batch pair fits without it; it costs one extra forward.
        "gradient_checkpointing": True,
        # Mirrors the YAML. Watch the wall clock before raising it: the last 2xT4 run took
        # ~1h52m per epoch, so 5 epochs is ~9.3h and will not finish inside a Kaggle
        # session. Lower it *here and in the YAML together* - the drift check compares them.
        # 3 is also the overfitting budget: hard_neg's best epoch was 1 of 4, with train
        # loss falling 0.649 -> 0.058 while val retrieval dropped monotonically after it.
        "epochs": 3,
        # groups per step; effective batch = this x n_gpus. The knob for *retained*
        # activation memory: one graph is held until backward, so stored activations
        # scale with tokens per step and only this controls them.
        "batch_size": 2,
        # sequences per forward inside encode_chunked. Caps the *transient* per-forward
        # working set (all micro-forwards stay in one graph, so it does not reduce
        # retained activations) AND sets padding tightness: encode_chunked sorts by true
        # length and trims each micro-batch to its own width. The latter dominates - the
        # median document is 167 tokens against a 2048 batch-wide pad, so unsorted
        # chunking wastes ~65% of every FLOP. Measured: 20 -> 1.68x, 10 -> 2.21x,
        # 5 -> 2.54x; 10 takes nearly all of it without starving the GPU. 0 disables.
        "doc_micro_batch": 10,
        # A full-FT rate (2e-5) under-trains an adapter, but 2e-4 over 1296 groups drove
        # every checkpoint *below* the untrained baseline - drift, not learning.
        "lr": 5.0e-5,
        "weight_decay": 0.01,
        "warmup_ratio": 0.1,
        "grad_clip": 1.0,
        "num_workers": 2,
        # Cosine sims live in [-1,1] and teacher scores in [0,1]; at T=1.0 a softmax
        # over 20 candidates is near-uniform on both sides and the gradient is noise.
        "student_temp": 0.05,
        "teacher_temp": 0.2,
        # Must not exceed what the triplet files were built with: TripletDataset slices
        # negatives[:max_negatives], so a larger value here silently trains on fewer.
        "max_negatives": 8,
        "max_documents": 20,
    },
    "lora": {
        "r": 8,
        "alpha": 16,
        "dropout": 0.1,
        "target_modules": ["q_proj", "k_proj", "v_proj", "o_proj"],
    },
    "eval": {
        "top_k": 5,
        "relevance_top_m": 3,  # relevant = top-m docs by teacher_score per group
        # Persona-swap control: re-scores every val query under a rotated persona
        # (crammer->scholar->steady->crammer) against the same corpus embedding and logs
        # the matched-minus-swapped delta. Personas reach the retriever only through the
        # `Instruct:` prefix, so an encoder that ignores it still improves every headline
        # metric while personalising nothing. Cheap - the corpus embedding is reused.
        "persona_swap": True,
        # no-grad corpus + query encoding, so unconstrained by training batch_size;
        # rank 0 only, once per epoch.
        "eval_batch_size": 32,
    },
    # Base-model anchoring (hard_neg only). Penalises drift from the pretrained Qwen3
    # embedding, since the observed failure is that training moves the encoder away from a
    # baseline it never beats. Reference embeddings come from the same weights with the
    # adapter switched off, cached once at startup - no extra forward per step.
    "anchor": {
        # none | both | doc_frozen. doc_frozen encodes documents with the adapter off
        # entirely; it changes the serving contract, since the index must then be built
        # the same way. Two lambdas because personalisation lives on the query side only -
        # documents carry no persona, so the document tower should barely move.
        "mode": "both",
        "lambda_doc": 0.5,
        "lambda_query": 0.05,
    },
    "checkpoint_dir": OUTPUT_DIR,
}

Path(CFG["checkpoint_dir"]).mkdir(parents=True, exist_ok=True)
os.chdir(WORKDIR)

# torchrun launches a fresh interpreter, which can only be handed a *file*, not a
# Python dict. Writing CFG out also leaves the run reproducible from an artifact.
import yaml

CFG_PATH = str(Path(WORKDIR) / "train_ropg_generated.yaml")
Path(CFG_PATH).write_text(yaml.safe_dump(CFG, sort_keys=False), encoding="utf-8")
print("Config ready. cwd:", os.getcwd(), "| config:", CFG_PATH)
"""),
    md("""## Trainer

Verbatim copy of `src/rl/ropg_kd.py`, written to disk so `torchrun` can execute it.
Generated - edit the source module and re-run `notebooks/build_train_ropg_kd.py` instead."""),
    code("%%writefile ropg_kd_worker.py\n" + worker),
    md("""## Launch

`torchrun` starts one process per GPU; Jupyter shows their output as it arrives, and
`--tee` keeps a per-rank copy under `torchrun_logs/`. The health check runs on rank 0
inside the worker."""),
    code("""import torch

n_gpus = torch.cuda.device_count()
print(f"Visible GPUs: {n_gpus}")
for i in range(n_gpus):
    print(f"  cuda:{i} {torch.cuda.get_device_name(i)}")

# torchrun children are independent processes, so nothing this notebook does to the
# GPU can starve them - the old "never touch CUDA in the parent" rule was a spawn
# constraint and no longer applies.
"""),
    code("""# torchrun starts one process per GPU. The NCCL settings matter on Kaggle: the
# container gives NCCL a small /dev/shm and the two T4s have no NVLink, so its default
# transports can stall at init. The fallback path is slower, but LoRA gradients are
# ~5M params so the cost is irrelevant here.
!NCCL_SHM_DISABLE=1 NCCL_P2P_DISABLE=1 NCCL_DEBUG=WARN PYTHONUNBUFFERED=1 \\
    torchrun --standalone --nproc_per_node={n_gpus} \\
    --tee 3 --log-dir torchrun_logs \\
    ropg_kd_worker.py --config {CFG_PATH} \\
    ; echo "[torchrun exit $?]"
"""),
    md("""### If the run fails

- **Non-zero exit.** The cell ends with `[torchrun exit N]` — worth checking, since a
  `!` command does not otherwise fail the cell. The traceback is in the output above;
  per-rank copies are under `torchrun_logs/`, which is where a rank-1-only failure
  shows up.
- **Stalls at startup.** `init_process_group` is capped at 10 minutes, so a rendezvous
  problem now raises instead of hanging. Set `NCCL_DEBUG=INFO` to see the handshake.
- **Isolating DDP.** Run `--nproc_per_node=1` — that path never calls
  `init_process_group`, so if it also fails the problem is in the training code.
- **Out of memory - read the allocation size first.** Peak memory here is *not* stable
  step to step, so an OOM can land many epochs in and still not be a leak. The dominant
  transient is the attention score matrix at `rows x heads x width^2 x dtype`, where
  `rows` is `doc_micro_batch` and `width` is set by the longest document the shuffle put
  in that batch (2048 for ~10 of the corpus's 171 chunks, ~167 for the median one). Check
  the `Epoch N peak GPU` lines: flat across epochs means the peak belongs to the worst
  batch, climbing means something is genuinely being retained.
  1. Confirm the startup log says `attn_implementation=sdpa`. Under `eager` this buffer
     is materialized *and* upcast to fp32 - 2.5 GB for one 10-row micro-batch at 2048.
  2. Halve `doc_micro_batch` (10 -> 5). Halves that buffer directly. Costs throughput:
     small launches starve the T4, which is what made `doc_micro_batch: 2` so slow.
  3. Lower `training.batch_size`. The knob for *retained* activations - all micro-forwards
     stay in one autograd graph until `backward()` - but it also changes the effective
     batch (`batch_size x world_size`), so the loss curve stops being comparable.
- **Out of memory during `eval: corpus`.** Different site, same cause: `encode_texts` is
  unsorted, so one long chunk widens a whole `eval.eval_batch_size` batch. It is `no_grad`
  and rank-0-only, ~5% of an epoch, so drop it to 8 without thinking twice.
- **Never turn off `gradient_checkpointing` on a T4.** It is not a speed knob to trade
  away: one `batch_size: 1` step retains ~36 GB of activations without it against ~2.5 GB
  with it, so nothing fits in 16 GB. It costs one extra forward (~33%), while the sorted
  micro-batching in `encode_chunked` is worth ~2.2x - fix throughput there instead.
- **`ImportError: incompatible version of torchao`** during `get_peft_model`. The setup
  cell should have removed torchao; if the image reinstalls it, re-run that cell. No
  kernel restart is needed - torchrun starts fresh interpreters that re-import
  everything."""),
    md("""## Results

Epoch 0 is the untrained model: a fresh LoRA adapter is the identity function, so those
numbers are the frozen Qwen3-Embedding baseline (Rung 1) measured through this exact
pipeline. Everything after is compared against it."""),
    code("""import json
from pathlib import Path

log = Path(CFG["checkpoint_dir"]) / "training_log.json"
if log.exists():
    data = json.loads(log.read_text(encoding="utf-8"))
    print(f"Best epoch: {data['best_epoch']}  (world_size={data.get('world_size', 1)})")
    top_k = CFG["eval"]["top_k"]
    ks = range(1, top_k + 1)
    for e in data["epoch_metrics"]:
        # Epoch 0 has no train_loss - it is a validation pass, not a trained epoch.
        head = "baseline (untrained)" if e["epoch"] == 0 else f"epoch {e['epoch']}"
        line = f"  {head}:"
        if "train_loss" in e:
            line += f" train {e['train_loss']:.4f} |"
        line += f" val {e['val_loss']:.4f}"
        print(line)
        if f"ndcg@{top_k}" in e:
            print("      nDCG@1..%d  %s" % (top_k, " ".join(f"{e[f'ndcg@{k}']['overall']:.3f}" for k in ks)))
            print("      Hit@1..%d   %s" % (top_k, " ".join(f"{e[f'hit@{k}']['overall']:.3f}" for k in ks)))
            rec = e[f"recall@{top_k}"]
            print(f"      Recall@{top_k} {rec['overall']:.4f} | MRR {e['mrr']['overall']:.4f}")
            for persona in sorted(k for k in rec if k != "overall"):
                print(f"        {persona:<9} nDCG@{top_k} {e[f'ndcg@{top_k}'][persona]:.4f}"
                      f" | Recall@{top_k} {rec[persona]:.4f} | MRR {e['mrr'][persona]:.4f}")
else:
    print(f"No training log at {log}")
"""),
    md("""## Significance vs. the baseline

Each epoch scores the *same* val queries as epoch 0, so the comparison is **paired** and
must be tested that way. Marginal confidence intervals on two means overlap far more often
than the paired difference contains zero — with ~276 queries a single epoch's interval is
roughly ±0.04 wide, enough to hide a real gain of that size. Resampling the queries and
taking the difference each time cancels the shared query difficulty, which is what makes
the test sharp enough to be worth running.

This cell only answers *"did this run beat its own untrained baseline?"*. For
**arm-vs-arm** comparison (run B against the unanchored run A control), per-persona
breakdowns, permutation p-values with Holm correction across the metric family, and the
persona-swap contrast, download `training_log.json` and use the offline tool:

```bash
uv run python benchmarks/compare_runs.py runA_log.json runB_log.json
uv run python benchmarks/compare_runs.py runB_log.json --swap
```

It also verifies that two arms' epoch-0 rows are identical, which is the check that
proves nothing leaked into the eval path between them."""),
    code("""import numpy as np

if log.exists() and any("per_query" in e for e in data["epoch_metrics"]):
    rng = np.random.default_rng(CFG["seed"])
    B = 5000
    epochs = {e["epoch"]: e["per_query"] for e in data["epoch_metrics"] if "per_query" in e}
    base = epochs.get(0)
    if base is None:
        print("No epoch-0 baseline in this log - nothing to compare against.")
    else:
        # Pairing is by position: group order and the skip decision depend only on the
        # data, never on the model, so index i is the same query in every epoch.
        n = len(base["mrr"])
        idx = rng.integers(0, n, (B, n))
        # Headline pair first (docs/experiment-design.md). judged@K is a diagnostic,
        # not a quality score: a fall there means nDCG is grading an increasingly
        # out-of-pool ranking rather than a worse one.
        names = ["ndcg@1", f"recall@{top_k}", "mrr", f"ndcg@{top_k}", f"hit@{top_k}"]
        names += [f"judged@{top_k}"] if f"judged@{top_k}" in base else []
        for ep in sorted(k for k in epochs if k != 0):
            print(f"epoch {ep} vs baseline   (n={n} queries, {B} bootstrap resamples)")
            for name in names:
                a, b = np.array(base[name]), np.array(epochs[ep][name])
                if a.shape != b.shape:
                    print(f"  {name:<10} skipped - length mismatch, pairing is unsafe")
                    continue
                d = b - a
                lo, hi = np.percentile(d[idx].mean(1), [2.5, 97.5])
                flag = "" if (lo > 0 or hi < 0) else "   (CI includes 0)"
                print(f"  {name:<10} {a.mean():.4f} -> {b.mean():.4f}"
                      f"   {d.mean():+.4f}  95% CI [{lo:+.4f}, {hi:+.4f}]{flag}")
else:
    print("No per-query vectors in the log - re-run training to enable paired testing.")
"""),
    md(
        "## Config drift check\n\nThe inline `CFG` above duplicates `configs/train_ropg.yaml`. When the repo is\nreachable, compare them — this is the check that would have caught the earlier\n`lr`, `max_seq_length` and `best_metric` drift."
    ),
    code("""import yaml
from pathlib import Path

_candidates = [Path("configs/train_ropg.yaml"), Path("../configs/train_ropg.yaml")]
_cfg_path = next((p for p in _candidates if p.exists()), None)

if _cfg_path is None:
    print("configs/train_ropg.yaml not reachable — skipping drift check.")
else:
    ref = yaml.safe_load(_cfg_path.read_text(encoding="utf-8"))
    # Paths and checkpoint_dir are runtime-specific and expected to differ.
    SKIP = {("data", "train_data"), ("data", "corpus_path"), ("checkpoint_dir",)}

    def walk(a, b, path=()):
        if path in SKIP:
            return
        if isinstance(a, dict) and isinstance(b, dict):
            for k in sorted(set(a) | set(b)):
                if k not in a:
                    print(f"  MISSING in notebook CFG: {'.'.join(path + (k,))} = {b[k]!r}")
                elif k not in b:
                    print(f"  EXTRA in notebook CFG:   {'.'.join(path + (k,))} = {a[k]!r}")
                else:
                    walk(a[k], b[k], path + (k,))
        elif a != b:
            print(f"  DRIFT {'.'.join(path)}: notebook={a!r} yaml={b!r}")

    print(f"Comparing CFG against {_cfg_path}:")
    walk(CFG, ref)
    print("Done. No lines above means the two agree.")
"""),
    md("## Download"),
    code("""import subprocess
from pathlib import Path

if RUNTIME != "colab":
    out = Path(CFG["checkpoint_dir"])
    subprocess.run(
        ["zip", "-r", "ropg_kd_model.zip", out.name + "/checkpoint-best", out.name + "/training_log.json"],
        cwd=str(out.parent),
        check=True,
    )
    print(f"{out.parent / 'ropg_kd_model.zip'} created.")
else:
    print("Colab: checkpoints already on Google Drive - skipping zip.")
"""),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

out = ROOT / "notebooks" / "train_ropg_kd.ipynb"
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
print(f"wrote {out} ({len(cells)} cells, worker={len(worker.splitlines())} lines)")
