"""Regenerate the self-contained Kaggle DPO training notebook from repository sources."""

from __future__ import annotations

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONFIG_TEXT = (ROOT / "configs" / "train_dpo.yaml").read_text(encoding="utf-8")
TRAINER_SOURCE = (ROOT / "src" / "rl" / "dpo_train.py").read_text(encoding="utf-8")
REWRITER_SOURCE = (ROOT / "src" / "rag" / "rewriter.py").read_text(encoding="utf-8")
COMPARISON_SOURCE = (ROOT / "benchmarks" / "compare_dpo_rewriters.py").read_text(encoding="utf-8")

# The notebook writes the small local package tree it needs. Pair generation is deliberately
# absent, so inline its format constant instead of shipping a large, unused API pipeline.
TRAINER_WORKER = TRAINER_SOURCE.replace(
    "    from data.gen_dpo_data import DPO_OUTPUT_FORMAT_VERSION\n",
    "    DPO_OUTPUT_FORMAT_VERSION = 1\n",
)
assert TRAINER_WORKER != TRAINER_SOURCE, "DPO format-version import was not inlined"
assert "from data.gen_dpo_data import" not in TRAINER_WORKER

SOURCE_FILES = {
    "src/rl/dpo_train.py": TRAINER_WORKER,
    "src/rag/rewriter.py": REWRITER_SOURCE,
    "src/rag/llm.py": (ROOT / "src" / "rag" / "llm.py").read_text(encoding="utf-8"),
    "src/personalization/profiles.py": (
        ROOT / "src" / "personalization" / "profiles.py"
    ).read_text(encoding="utf-8"),
    "src/data/questions.py": (ROOT / "src" / "data" / "questions.py").read_text(encoding="utf-8"),
    "src/data/settings.py": (ROOT / "src" / "data" / "settings.py").read_text(encoding="utf-8"),
    "benchmarks/compare_dpo_rewriters.py": COMPARISON_SOURCE,
}
for relative_path, source in SOURCE_FILES.items():
    compile(source, relative_path, "exec")
train_function_source = TRAINER_WORKER[TRAINER_WORKER.index("def train(") :]
assert train_function_source.index("from unsloth import FastLanguageModel") < (
    train_function_source.index("from trl import DPOConfig")
)
# Both GPU entry points must load one whole replica per device. Sharding a 4-bit Qwen3-4B
# over both T4s breaks DDP replication and puts token ids and the tied embedding on
# different devices during generation.
assert 'device_map={"": local_rank}' in TRAINER_WORKER
assert 'loader_kwargs["device_map"] = {"": device_index}' in REWRITER_SOURCE

PACKAGE_PINS = (
    "unsloth==2026.8.22 trl==0.24.0 transformers==4.57.6 datasets==4.3.0 "
    "peft==0.18.0 accelerate==1.14.0"
)
# The tournament judge is a Gemini model. Metis serves that family over Google's native
# GenAI protocol, so the OpenAI SDK cannot reach it and this package is not optional.
JUDGE_PIN = "google-genai==2.20.0"

# This experiment uses bitsandbytes QLoRA. Remove Kaggle's optional TorchAO package so PEFT
# cannot dispatch into a TorchAO build compiled for a different PyTorch release.
PIP_COMMAND = (
    "!pip install -q "
    + " ".join(f'"{pin}"' for pin in [*PACKAGE_PINS.split(), JUDGE_PIN])
    + "\n!pip uninstall -q -y torchao"
)


def markdown(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


source_payload = json.dumps(SOURCE_FILES, ensure_ascii=False, sort_keys=True)
config_literal = repr(CONFIG_TEXT)

cells = [
    markdown(
        """# DPO-family query-rewriter training

Generated by `notebooks/build_train_dpo.py`. Do not hand-edit this notebook. Change the
repository source or `configs/train_dpo.yaml`, then rebuild it.

The same trainer runs standard DPO, WPO, and robust DPO. Kaggle uses one QLoRA replica per
T4 through native TRL/Accelerate DDP. The target global batch stays 8. The retriever is not
part of this stage.

Run order — one non-interactive pass, top to bottom:

1. Package setup, source materialization, runtime config.
2. Health and exact data preflight, once, on the first arm.
3. Two-step DDP smoke, once, on the first arm.
4. Full three-epoch training for every arm in `ARMS`, each isolated from the others.
5. Deterministic Qwen outputs plus the cached temperature-zero Grok baseline.
6. Gemini tournament, which runs only when every arm in `ARMS` has a promoted adapter.
7. Export, status table, and `run_status.json`.

Set `SEED`, and `WINNING_VARIANT` for replication seeds. Nothing else needs touching
between runs: this notebook is built for Save & Run All. A failing arm is recorded and
skipped rather than aborting the arms that already finished.
"""
    ),
    code(PIP_COMMAND),
    code(
        """import os
from pathlib import Path

os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
RUNTIME = "kaggle"  # "kaggle" | "colab" | "local"
ARMS = ["dpo", "wpo", "robust_dpo"]  # trained in order within a single batch run
SEED = 42
WINNING_VARIANT = "wpo"  # read only when SEED != 42: the seed-42 tournament winner
if SEED != 42:
    ARMS = ["dpo", WINNING_VARIANT]
GDRIVE_BASE = "/content/drive/MyDrive/simurgh-data"

if RUNTIME == "kaggle":
    from kaggle_secrets import UserSecretsClient

    DATA_ROOT = Path("/kaggle/input/datasets/alirezahsn/simurgh-data")
    OUTPUT_ROOT = Path("/kaggle/working/dpo")
    WORKDIR = Path("/kaggle/working/dpo_job")
    secrets = UserSecretsClient()
    for key in (
        "REWRITER_BASE_URL",
        "REWRITER_API_KEY",
        "DPO_EVAL_BASE_URL",
        "DPO_EVAL_API_KEY",
        "DPO_EVAL_MODEL",
    ):
        try:
            os.environ[key] = secrets.get_secret(key)
        except Exception:
            pass
elif RUNTIME == "colab":
    from google.colab import drive, userdata

    drive.mount("/content/drive")
    DATA_ROOT = Path(GDRIVE_BASE)
    OUTPUT_ROOT = DATA_ROOT / "dpo"
    WORKDIR = Path("/content/dpo_job")
    for key in (
        "REWRITER_BASE_URL",
        "REWRITER_API_KEY",
        "DPO_EVAL_BASE_URL",
        "DPO_EVAL_API_KEY",
        "DPO_EVAL_MODEL",
    ):
        value = userdata.get(key)
        if value:
            os.environ[key] = value
else:
    DATA_ROOT = Path("data")
    OUTPUT_ROOT = Path("data/rl/dpo_notebook")
    WORKDIR = Path(".dpo_job")

WORKDIR.mkdir(parents=True, exist_ok=True)
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
os.chdir(WORKDIR)
os.environ["PYTHONPATH"] = str(WORKDIR / "src")
print("Runtime:", RUNTIME, "| ARMS:", ARMS, "| SEED:", SEED, "| cwd:", WORKDIR)
"""
    ),
    markdown("## Materialize the exact repository contract"),
    code(
        f"""import json

SOURCE_FILES = json.loads({source_payload!r})
for relative_path, content in SOURCE_FILES.items():
    path = WORKDIR / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
for package in ("rl", "rag", "personalization", "data"):
    (WORKDIR / "src" / package / "__init__.py").touch()

CONFIG_YAML = {config_literal}
CONFIG_PATH = WORKDIR / "train_dpo_embedded.yaml"
CONFIG_PATH.write_text(CONFIG_YAML, encoding="utf-8")
print(f"Wrote {{len(SOURCE_FILES)}} source files and {{CONFIG_PATH}}")
"""
    ),
    code(
        """import yaml

base_config = yaml.safe_load(CONFIG_YAML)
base_config["data"]["train_path"] = str(DATA_ROOT / "dpo" / "train.jsonl")
base_config["data"]["val_path"] = str(DATA_ROOT / "dpo" / "val.jsonl")
base_config["data"]["questions_dir"] = str(DATA_ROOT / "questions")
base_config["training"]["run_root"] = str(OUTPUT_ROOT / "runs")
base_config["generation"]["output_root"] = str(OUTPUT_ROOT / "outputs")
base_config["comparison"]["output_root"] = str(OUTPUT_ROOT / "comparisons")

FULL_CONFIG_PATH = WORKDIR / "train_dpo_runtime.yaml"
FULL_CONFIG_PATH.write_text(yaml.safe_dump(base_config, sort_keys=False), encoding="utf-8")
smoke_config = yaml.safe_load(yaml.safe_dump(base_config))
smoke_config["training"]["run_root"] = str(OUTPUT_ROOT / "smoke_runs")
SMOKE_CONFIG_PATH = WORKDIR / "train_dpo_smoke.yaml"
SMOKE_CONFIG_PATH.write_text(yaml.safe_dump(smoke_config, sort_keys=False), encoding="utf-8")
print("Runtime paths applied. Behavioral values still come from the embedded YAML.")
"""
    ),
    markdown("## Health and exact data preflight"),
    code(
        """import importlib.metadata
import subprocess
import sys

import torch

n_gpus = torch.cuda.device_count()
print("Visible GPUs:", n_gpus)
for index in range(n_gpus):
    print(f"  cuda:{index} {torch.cuda.get_device_name(index)}")
assert n_gpus == 2, f"This DDP notebook requires two visible T4-class GPUs, got {n_gpus}"

# google-genai belongs here too: the tournament runs hours after this cell, and a silently
# failed install would only surface once every arm had already trained.
for package in (
    "unsloth",
    "trl",
    "transformers",
    "datasets",
    "peft",
    "accelerate",
    "google-genai",
):
    print(f"{package}={importlib.metadata.version(package)}")
try:
    torchao_version = importlib.metadata.version("torchao")
except importlib.metadata.PackageNotFoundError:
    print("torchao=not installed")
else:
    raise RuntimeError(
        f"torchao=={torchao_version} is still installed; rerun the package setup cell"
    )
for key in (
    "REWRITER_BASE_URL",
    "REWRITER_API_KEY",
    "DPO_EVAL_BASE_URL",
    "DPO_EVAL_API_KEY",
    "DPO_EVAL_MODEL",
):
    print(f"{key} present: {bool(os.environ.get(key))}")
print("Expected screening calls: 272 prompts x 10 pairs = 2720")
print("Expected replication calls: 272 prompts x 5 pairs x 2 seeds = 2720")
print("Total judge calls: 5440")

preflight_env = os.environ.copy()
preflight_env.update({"WORLD_SIZE": str(n_gpus), "RANK": "0"})
subprocess.run(
    [
        sys.executable,
        "-m",
        "rl.dpo_train",
        "--config",
        str(FULL_CONFIG_PATH),
        "--arm",
        ARMS[0],
        "--seed",
        str(SEED),
        "--preflight-only",
    ],
    check=True,
    env=preflight_env,
)
"""
    ),
    markdown("## Two-optimizer-step DDP smoke, first arm only"),
    code(
        """import subprocess

# The arms differ only in loss configuration, so one smoke proves the DDP launch path for
# all of them. Repeating it per arm would burn several minutes of a batch run for nothing.
smoke_command = [
    "torchrun",
    "--standalone",
    "--nproc_per_node=2",
    "--tee",
    "3",
    "--log-dir",
    str(OUTPUT_ROOT / "smoke_torchrun_logs"),
    "-m",
    "rl.dpo_train",
    "--config",
    str(SMOKE_CONFIG_PATH),
    "--arm",
    ARMS[0],
    "--seed",
    str(SEED),
    "--max-steps",
    "2",
]
subprocess.run(smoke_command, check=True, env=os.environ.copy())
"""
    ),
    markdown("## Full three-epoch DDP training"),
    code(
        """import subprocess

STAGE_STATUS = {}


def record(stage, error=None):
    STAGE_STATUS[stage] = "ok" if error is None else f"failed: {error}"
    print(f"[{stage}] {STAGE_STATUS[stage]}")


for arm in ARMS:
    full_command = [
        "torchrun",
        "--standalone",
        "--nproc_per_node=2",
        "--tee",
        "3",
        "--log-dir",
        str(OUTPUT_ROOT / "torchrun_logs" / f"{arm}-seed-{SEED}"),
        "-m",
        "rl.dpo_train",
        "--config",
        str(FULL_CONFIG_PATH),
        "--arm",
        arm,
        "--seed",
        str(SEED),
    ]
    # An arm that dies must not cost the arms that already finished their three epochs.
    try:
        subprocess.run(full_command, check=True, env=os.environ.copy())
    except subprocess.CalledProcessError as error:
        record(f"train:{arm}", error)
    else:
        record(f"train:{arm}")
"""
    ),
    markdown("## Deterministic model-output generation"),
    code(
        """run_root = Path(base_config["training"]["run_root"])
promoted = {arm: run_root / arm / f"seed-{SEED}" for arm in ARMS}
trained = [arm for arm in ARMS if (promoted[arm] / "dpo_best").is_dir()]
print("Arms with a promoted adapter:", trained)
if not trained:
    record("generate", "no promoted adapter to generate from")
else:
    generation_command = [
        sys.executable,
        str(WORKDIR / "benchmarks" / "compare_dpo_rewriters.py"),
        "--config",
        str(FULL_CONFIG_PATH),
        "--comparison-seed",
        str(SEED),
        "--generate-only",
    ]
    for arm in trained:
        generation_command.extend(["--run", f"{arm}={promoted[arm]}"])
    try:
        subprocess.run(generation_command, check=True, env=os.environ.copy())
    except subprocess.CalledProcessError as error:
        record("generate", error)
    else:
        record("generate")
"""
    ),
    markdown("## Gemini blind pairwise tournament"),
    code(
        """missing = [arm for arm in ARMS if not (promoted[arm] / "dpo_best").is_dir()]
if missing:
    print("Skipping the tournament; these arms have no promoted adapter:", missing)
    record("tournament", f"missing arms {missing}")
elif STAGE_STATUS.get("generate") != "ok":
    print("Skipping the tournament; deterministic output generation did not succeed.")
    record("tournament", "generation incomplete")
else:
    if SEED == 42:
        selected_pairs = []  # all 10 pairs among the five candidates
    else:
        selected_pairs = [
            f"dpo:{WINNING_VARIANT}",
            "base_qwen:dpo",
            "dpo:grok",
            f"base_qwen:{WINNING_VARIANT}",
            f"{WINNING_VARIANT}:grok",
        ]
    tournament_command = [
        sys.executable,
        str(WORKDIR / "benchmarks" / "compare_dpo_rewriters.py"),
        "--config",
        str(FULL_CONFIG_PATH),
        "--comparison-seed",
        str(SEED),
    ]
    for arm in ARMS:
        tournament_command.extend(["--run", f"{arm}={promoted[arm]}"])
    for selected_pair in selected_pairs:
        tournament_command.extend(["--pair", selected_pair])
    try:
        subprocess.run(tournament_command, check=True, env=os.environ.copy())
    except subprocess.CalledProcessError as error:
        record("tournament", error)
    else:
        record("tournament")
"""
    ),
    markdown("## Export artifacts"),
    code(
        """import shutil

archive = shutil.make_archive(
    str(Path("/kaggle/working") / f"dpo-seed-{SEED}"),
    "zip",
    root_dir=OUTPUT_ROOT,
)
print("Created:", archive)

status_path = OUTPUT_ROOT / "run_status.json"
status_path.write_text(json.dumps(STAGE_STATUS, indent=2, sort_keys=True), encoding="utf-8")
print("=" * 72)
for stage in sorted(STAGE_STATUS):
    print(f"{stage:20s} {STAGE_STATUS[stage]}")
print("=" * 72)
failed = sorted(stage for stage, state in STAGE_STATUS.items() if state != "ok")
# Kaggle discards the output of a failed batch version, so a partially successful run must
# exit cleanly and report through the table above and run_status.json. Only a run that
# produced nothing at all raises, since it has no artifact left to preserve.
if failed and len(failed) == len(STAGE_STATUS):
    raise RuntimeError(f"Every stage failed: {failed}")
if failed:
    print("INCOMPLETE RUN. Failed stages:", failed)
else:
    print("All stages succeeded.")
"""
    ),
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
serialized = json.dumps(notebook, ensure_ascii=False, indent=1) + "\n"

for arm in ("dpo", "wpo", "robust_dpo"):
    assert arm in serialized
for pin in (*PACKAGE_PINS.split(), JUDGE_PIN):
    assert pin in serialized
for required in (
    "max_prompt_length",
    "max_completion_length",
    "over_limit",
    "torchrun",
    "--nproc_per_node=2",
    "do_sample",
    "grok-4-1-fast",
    "DPO_EVAL_BASE_URL",
    "DPO_EVAL_API_KEY",
    "DPO_EVAL_MODEL",
    "GeminiClient(",
    "thinking_level",
    "judge_thinking_level",
    "response_schema",
    "judge_max_tokens: 512",
    "pip uninstall -q -y torchao",
    "STAGE_STATUS",
    "run_status.json",
    "Skipping the tournament",
    "ARMS = [",
):
    assert required in serialized, f"Generated notebook is missing {required!r}"
for forbidden in ("from rag.pipeline", "import faiss", '"knowledge_base"', '"index_path"'):
    assert forbidden not in serialized, f"Retriever dependency leaked into notebook: {forbidden}"
# Gemini 3.5 and newer reject the `thinking_budget` argument with a 400, so it must not come
# back. Match the assignment, not the word: the docs and comments name the dead field.
assert "thinking_budget=" not in serialized, "Notebook still sends the rejected thinking_budget"
# The three seed-42 pathologies must not creep back in through the inlined config. Check the
# parsed values, not substrings: "epochs: 1" also matches "epochs: 10". See
# docs/results/dpo-arms-seed42-v1.md.
inlined_config = yaml.safe_load(CONFIG_TEXT)
assert inlined_config["training"]["epochs"] == 1, "Epochs above one only added memorization"
assert inlined_config["training"]["metric_for_best_model"] == "eval_rewards/accuracies", (
    "eval_loss is not a valid selector: robust is unbounded below and WPO is weight-scaled"
)
assert inlined_config["training"]["greater_is_better"] is True
assert all(arm["rpo_alpha"] == 1.0 for arm in inlined_config["arms"].values()), (
    "Every arm needs its supervised NLL anchor against likelihood displacement"
)
# Assert batch-mode invariants against the raw cell text: the serialized notebook escapes
# every quote, so the same checks against `serialized` would silently never match.
cell_text = "".join("".join(cell["source"]) for cell in cells)
assert 'ARMS = ["dpo", "wpo", "robust_dpo"]' in cell_text
assert 'ARM = "dpo"' not in cell_text, "Notebook still trains a single scalar ARM"
assert cell_text.count("except subprocess.CalledProcessError") == 3, (
    "Training, generation, and the tournament must each contain their own failure handler"
)

output_path = ROOT / "notebooks" / "train_dpo.ipynb"
output_path.write_text(serialized, encoding="utf-8")
print(f"Wrote {output_path}")
