"""DPO training of the query rewriter (Qwen3-4B + LoRA).

Stage 2 of Simurgh's two-stage training. Loads preference pairs generated by
src/data/gen_dpo_data.py and fine-tunes Qwen3-4B with Direct Preference Optimization.

Runs on GPU (Kaggle / university cluster). Install the training extra first:
    uv sync --extra embedding --extra training

Typical usage:
    uv run python -m rl.dpo_train --config configs/phase4_dpo_rewriter.yaml
"""

from __future__ import annotations

import argparse
import json
import logging
import random
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)


# ── Data loading ──────────────────────────────────────────────────────────────


def load_pairs(path: str | Path) -> list[dict]:
    """Load preference pairs from a JSONL file, refusing formats the trainer cannot use.

    The version check is the guard against training on stem-only pairs: those rows carry a
    bare question stem in ``query``, while the retriever this rewriter feeds was distilled
    on the complete rendered question. Such pairs load and train without error, so nothing
    but this check would reveal the mismatch.
    """
    from data.gen_dpo_data import DPO_OUTPUT_FORMAT_VERSION

    pairs = []
    for line_number, line in enumerate(
        Path(path).read_text(encoding="utf-8").splitlines(), start=1
    ):
        if not line.strip():
            continue
        record = json.loads(line)
        version = record.get("format_version")
        if version != DPO_OUTPUT_FORMAT_VERSION:
            raise ValueError(
                f"{path} line {line_number} has format version {version!r}, expected "
                f"{DPO_OUTPUT_FORMAT_VERSION}; regenerate the pairs with "
                "src/data/gen_dpo_data.py"
            )
        pairs.append(record)
    return pairs


def pairs_to_dataset(pairs: list[dict], tokenizer=None):
    """Convert raw pairs to a HuggingFace Dataset for TRL's DPOTrainer.

    TRL expects columns: prompt, chosen, rejected.
    The prompt is the full rewriter input (system + user); chosen/rejected are the rewrites.

    When tokenizer is provided, apply_chat_template is used with enable_thinking=False so
    Qwen3's reasoning chain is suppressed — without this, <think>…</think> tokens would
    appear in every completion and corrupt the DPO signal.
    """
    from datasets import Dataset

    from personalization.profiles import render_profile
    from rag.rewriter import _build_rewrite_prompt

    rows = []
    for p in pairs:
        msgs = _build_rewrite_prompt(render_profile(p["persona_id"]), p["query"])
        if tokenizer is not None:
            prompt = tokenizer.apply_chat_template(
                msgs,
                tokenize=False,
                add_generation_prompt=True,
                enable_thinking=False,
            )
        else:
            prompt = "\n\n".join(m["content"] for m in msgs)
        rows.append(
            {
                "prompt": prompt,
                "chosen": p["chosen"],
                "rejected": p["rejected"],
            }
        )
    return Dataset.from_list(rows)


# ── Training ──────────────────────────────────────────────────────────────────


def train(config: dict) -> None:
    import torch
    from unsloth import FastModel
    from trl import DPOConfig, DPOTrainer

    dpo_cfg = config["dpo"]
    pairs_path = config["preference_pairs"]["output_path"]
    checkpoint_dir = Path(dpo_cfg["checkpoint_dir"])
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    seed = config.get("seed", 42)
    random.seed(seed)
    torch.manual_seed(seed)

    device = dpo_cfg.get("device", "cuda" if torch.cuda.is_available() else "cpu")
    logger.info("Device: %s", device)

    train_pairs = load_pairs(pairs_path)
    logger.info("Loaded %d train pairs from %s", len(train_pairs), pairs_path)

    val_path = config["preference_pairs"].get("val_path")
    if val_path:
        val_pairs = load_pairs(val_path)
        logger.info("Loaded %d val pairs from %s", len(val_pairs), val_path)
    else:
        random.shuffle(train_pairs)
        val_size = max(1, int(len(train_pairs) * dpo_cfg.get("val_fraction", 0.1)))
        val_pairs = train_pairs[:val_size]
        train_pairs = train_pairs[val_size:]
        logger.info("Train: %d | Val: %d (internal split)", len(train_pairs), len(val_pairs))

    model_name = dpo_cfg.get("model", "Qwen/Qwen3-4B")
    logger.info("Loading model via Unsloth: %s", model_name)
    model, tokenizer = FastModel.from_pretrained(
        model_name=model_name,
        dtype=None,
        max_seq_length=dpo_cfg.get("max_length", 512),
        load_in_4bit=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    train_dataset = pairs_to_dataset(train_pairs, tokenizer)
    val_dataset = pairs_to_dataset(val_pairs, tokenizer)

    model = FastModel.get_peft_model(
        model,
        r=dpo_cfg.get("lora_r", 16),
        lora_alpha=dpo_cfg.get("lora_alpha", 32),
        lora_dropout=dpo_cfg.get("lora_dropout", 0.0),
        target_modules=dpo_cfg.get("lora_target_modules", ["q_proj", "v_proj"]),
        bias="none",
        use_gradient_checkpointing="unsloth",
    )
    model.print_trainable_parameters()

    training_args = DPOConfig(
        output_dir=str(checkpoint_dir),
        num_train_epochs=dpo_cfg.get("epochs", 2),
        per_device_train_batch_size=dpo_cfg.get("batch_size", 2),
        gradient_accumulation_steps=dpo_cfg.get("gradient_accumulation_steps", 4),
        learning_rate=dpo_cfg.get("lr", 5e-5),
        beta=dpo_cfg.get("beta", 0.1),
        max_length=dpo_cfg.get("max_length", 512),
        max_prompt_length=dpo_cfg.get("max_prompt_length", 400),
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        seed=seed,
        fp16=device == "cuda",
        gradient_checkpointing=True,
        logging_steps=10,
        report_to="none",
    )

    trainer = DPOTrainer(
        model=model,
        ref_model=None,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        processing_class=tokenizer,
    )

    logger.info("Starting DPO training...")
    trainer.train()
    trainer.save_model(str(checkpoint_dir / "dpo_best"))
    logger.info("DPO training complete. Best checkpoint: %s", checkpoint_dir / "dpo_best")


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description="DPO training of the query rewriter.")
    parser.add_argument("--config", required=True, help="Path to phase4 YAML config.")
    args = parser.parse_args()
    with open(args.config, encoding="utf-8") as f:
        config = yaml.safe_load(f)
    train(config)


if __name__ == "__main__":
    main()
