"""DPO training of the query rewriter (Gemma-4-E4B + LoRA).

Stage 2 of Simurgh's two-stage training. Loads preference pairs generated by
preference_pairs.py and fine-tunes Gemma-4-E4B with Direct Preference Optimization.

Runs on GPU (Kaggle / university cluster). Install the training extra first:
    uv sync --extra embedding --extra training

Typical usage:
    uv run python -m rl.dpo_train --config configs/phase4_dpo_rewriter.yaml
"""

from __future__ import annotations

import argparse
import json
import logging
import random
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)


# ── Data loading ──────────────────────────────────────────────────────────────


def load_pairs(path: str | Path) -> list[dict]:
    """Load preference pairs from a JSONL file."""
    pairs = []
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if line.strip():
            pairs.append(json.loads(line))
    return pairs


def pairs_to_dataset(pairs: list[dict]):
    """Convert raw pairs to a HuggingFace Dataset for TRL's DPOTrainer.

    TRL expects columns: prompt, chosen, rejected.
    The prompt is the full rewriter input (system + user); chosen/rejected are the rewrites.
    """
    from datasets import Dataset

    from rag.rewriter import _build_rewrite_prompt

    rows = []
    for p in pairs:
        msgs = _build_rewrite_prompt(p["profile_rendered"], p["query"])
        # Format as a single string: system\n\nuser  (DPOTrainer accepts message lists too,
        # but a flat string is simpler and avoids chat-template issues across model families).
        prompt = "\n\n".join(m["content"] for m in msgs)
        rows.append(
            {
                "prompt": prompt,
                "chosen": p["chosen"],
                "rejected": p["rejected"],
            }
        )
    return Dataset.from_list(rows)


# ── Training ──────────────────────────────────────────────────────────────────


def train(config: dict) -> None:
    import torch
    from peft import LoraConfig, TaskType, get_peft_model
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from trl import DPOConfig, DPOTrainer

    dpo_cfg = config["dpo"]
    pairs_path = config["preference_pairs"]["output_path"]
    checkpoint_dir = Path(dpo_cfg["checkpoint_dir"])
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    seed = config.get("seed", 42)
    random.seed(seed)
    torch.manual_seed(seed)

    device = dpo_cfg.get("device", "cuda" if torch.cuda.is_available() else "cpu")
    logger.info("Device: %s", device)

    pairs = load_pairs(pairs_path)
    logger.info("Loaded %d preference pairs from %s", len(pairs), pairs_path)

    random.shuffle(pairs)
    val_size = max(1, int(len(pairs) * dpo_cfg.get("val_fraction", 0.1)))
    val_pairs = pairs[:val_size]
    train_pairs = pairs[val_size:]
    logger.info("Train: %d | Val: %d", len(train_pairs), len(val_pairs))

    train_dataset = pairs_to_dataset(train_pairs)
    val_dataset = pairs_to_dataset(val_pairs)

    model_name = dpo_cfg.get("model", "google/gemma-4-e4b")
    logger.info("Loading model: %s", model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.bfloat16 if device == "cuda" else torch.float32,
        device_map="auto" if device == "cuda" else None,
    )
    ref_model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.bfloat16 if device == "cuda" else torch.float32,
        device_map="auto" if device == "cuda" else None,
    )

    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=dpo_cfg.get("lora_r", 16),
        lora_alpha=dpo_cfg.get("lora_alpha", 32),
        lora_dropout=dpo_cfg.get("lora_dropout", 0.05),
        target_modules=dpo_cfg.get("lora_target_modules", ["q_proj", "v_proj"]),
        bias="none",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    training_args = DPOConfig(
        output_dir=str(checkpoint_dir),
        num_train_epochs=dpo_cfg.get("epochs", 2),
        per_device_train_batch_size=dpo_cfg.get("batch_size", 2),
        gradient_accumulation_steps=dpo_cfg.get("gradient_accumulation_steps", 4),
        learning_rate=dpo_cfg.get("lr", 5e-5),
        beta=dpo_cfg.get("beta", 0.1),
        max_length=dpo_cfg.get("max_length", 512),
        max_prompt_length=dpo_cfg.get("max_prompt_length", 400),
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        seed=seed,
        bf16=device == "cuda",
        logging_steps=10,
        report_to="none",
    )

    trainer = DPOTrainer(
        model=model,
        ref_model=ref_model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        processing_class=tokenizer,
    )

    logger.info("Starting DPO training...")
    trainer.train()
    trainer.save_model(str(checkpoint_dir / "dpo_best"))
    logger.info("DPO training complete. Best checkpoint: %s", checkpoint_dir / "dpo_best")


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description="DPO training of the query rewriter.")
    parser.add_argument("--config", required=True, help="Path to phase4 YAML config.")
    args = parser.parse_args()
    with open(args.config, encoding="utf-8") as f:
        config = yaml.safe_load(f)
    train(config)


if __name__ == "__main__":
    main()
