"""Generate DPO preference pairs for the query rewriter.

For each (question, persona) in the train split:
  1. Sample N rewrites from the current rewriter policy (Gemma-4-E4B via an
     OpenAI-compatible endpoint — e.g. LMStudio or llama.cpp serving the model).
  2. For each rewrite: retrieve top-K docs → generate an answer with the frozen generator.
  3. Score each answer with the labeling judge (must differ in family from the eval judge).
  4. Write (chosen, rejected) pair — highest and lowest scored rewrites — to a JSONL file.

The script is resumable: (question, persona) pairs already in the output file are skipped.

Typical usage:
    uv run python -m rl.preference_pairs --config configs/phase4_dpo_rewriter.yaml
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import yaml

from data.settings import OPENAI_API_KEY, OPENAI_BASE_URL
from personalization.profiles import render_profile, train_personas
from rag.llm import OpenAICompatClient
from rag.prompts import build_rag_prompt
from rl.scorer import _parse_score, load_questions

logger = logging.getLogger(__name__)

# ── Labeling judge prompt for DPO ────────────────────────────────────────────
# The labeling judge scores the *final answer* (not the document), on the same
# 1–10 rubric: persona fit + pedagogical quality + faithfulness to context.
# It MUST differ in model family from the eval judge — see docs/methodology.md.

_DPO_JUDGE_SYSTEM = (
    "You are an expert Persian-language educational assessor. "
    "You will be shown a student profile, a question, and an answer generated by a RAG system. "
    "Rate how well this answer serves the student, on a scale from 1 to 10.\n\n"
    "Scoring rubric:\n"
    "  10 — Answer perfectly matches the student's comprehension level, prior knowledge, "
    "learning goal, and explanation style; is faithful to the retrieved context.\n"
    "   7 — Mostly good but weak on one dimension (fit or faithfulness).\n"
    "   4 — Partially helpful but poorly calibrated to the student's needs.\n"
    "   1 — Unhelpful, misleading, or hallucinates beyond the provided context.\n\n"
    "Output ONLY a single integer between 1 and 10. No explanation."
)


def _answer_judge_prompt(query: str, profile_rendered: str, answer: str) -> list[dict[str, str]]:
    user = (
        f"Student profile: {profile_rendered}\n\n"
        f"Question: {query}\n\n"
        f"Answer:\n{answer}\n\n"
        "Quality score (1–10):"
    )
    return [
        {"role": "system", "content": _DPO_JUDGE_SYSTEM},
        {"role": "user", "content": user},
    ]


# ── Resumable output ─────────────────────────────────────────────────────────


def _load_done(output_path: Path) -> set[tuple[str, str, str]]:
    """Return (source, question_id, persona_id) triples already in the output file."""
    if not output_path.exists():
        return set()
    done: set[tuple[str, str, str]] = set()
    for line in output_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            rec = json.loads(line)
            done.add((rec["source"], rec["question_id"], rec["persona_id"]))
        except (json.JSONDecodeError, KeyError):
            continue
    return done


# ── Main ─────────────────────────────────────────────────────────────────────


def run(config: dict) -> None:
    from rag.dense_store import DenseStore
    from rag.embedder import BGE_M3Embedder

    pp_cfg = config["preference_pairs"]
    output_path = Path(pp_cfg["output_path"])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    n_rewrites = pp_cfg.get("n_rewrites", 4)
    exam_dir = pp_cfg.get("exam_dir", "data/exams/raw")

    # Rewriter policy — points at the Gemma-4-E4B local server.
    rw_cfg = pp_cfg["rewriter_llm"]
    rewriter_llm = OpenAICompatClient(
        base_url=rw_cfg.get("base_url", OPENAI_BASE_URL),
        api_key=rw_cfg.get("api_key", OPENAI_API_KEY),
        model=rw_cfg["model"],
        temperature=rw_cfg.get("temperature", 0.8),
        max_tokens=rw_cfg.get("max_tokens", 200),
    )

    # Frozen generator (same API model used in earlier rungs).
    gen_cfg = config["llm"]
    generator_llm = OpenAICompatClient(
        base_url=OPENAI_BASE_URL,
        api_key=OPENAI_API_KEY,
        model=gen_cfg["model"],
        temperature=gen_cfg.get("temperature", 0.2),
        max_tokens=gen_cfg.get("max_tokens", 800),
    )

    # Labeling judge (must differ in family from eval judge; configured separately).
    judge_cfg = pp_cfg["judge_llm"]
    judge_llm = OpenAICompatClient(
        base_url=OPENAI_BASE_URL,
        api_key=OPENAI_API_KEY,
        model=judge_cfg["model"],
        temperature=judge_cfg.get("temperature", 0.0),
        max_tokens=judge_cfg.get("max_tokens", 10),
    )

    # Dense retriever (ROPG-KD trained; reads the index from config).
    emb_cfg = config.get("embedder", {})
    embedder = BGE_M3Embedder(
        model_name=emb_cfg.get("model", "BAAI/bge-m3"),
        device=emb_cfg.get("device", "cpu"),
    )
    store = DenseStore(
        index_path=config["knowledge_base"]["index_path"],
        meta_path=config["knowledge_base"]["meta_path"],
        embedder=embedder,
    )
    top_k: int = config["retrieval"]["top_k"]
    prompt_variant: str = gen_cfg.get("prompt_variant", "en")

    questions = load_questions(exam_dir)
    personas = train_personas()
    done = _load_done(output_path)

    logger.info(
        "Questions: %d | Personas: %d | N rewrites: %d | Already done: %d",
        len(questions),
        len(personas),
        n_rewrites,
        len(done),
    )

    # Import the rewrite prompt builder from the rewriter module.
    from rag.rewriter import _build_rewrite_prompt

    with output_path.open("a", encoding="utf-8") as out_f:
        for q in questions:
            for persona in personas:
                key = (q["source"], q["id"], persona.id)
                if key in done:
                    continue

                profile_rendered = render_profile(persona.id)

                # 1. Sample N rewrites.
                rewrites: list[str] = []
                for _ in range(n_rewrites):
                    msgs = _build_rewrite_prompt(profile_rendered, q["stem"])
                    try:
                        rw = rewriter_llm.chat(msgs).strip()
                        if rw:
                            rewrites.append(rw)
                    except Exception as exc:
                        logger.warning("Rewrite failed: %s", exc)

                if len(rewrites) < 2:
                    logger.warning(
                        "Skipping q=%s persona=%s: only %d rewrites",
                        q["id"],
                        persona.id,
                        len(rewrites),
                    )
                    continue

                # 2–3. Retrieve → generate → score each rewrite.
                scored: list[tuple[float, str]] = []
                for rewrite in rewrites:
                    hits = store.search(rewrite, top_k)
                    messages = build_rag_prompt(rewrite, hits, variant=prompt_variant)
                    try:
                        answer = generator_llm.chat(messages)
                        judge_msgs = _answer_judge_prompt(q["stem"], profile_rendered, answer)
                        raw_score = judge_llm.chat(judge_msgs)
                        score = _parse_score(raw_score) or 0.0
                    except Exception as exc:
                        logger.warning("Pipeline call failed: %s", exc)
                        score = 0.0
                    scored.append((score, rewrite))

                scored.sort(key=lambda x: x[0])
                rejected_score, rejected_rewrite = scored[0]
                chosen_score, chosen_rewrite = scored[-1]

                if chosen_score <= rejected_score:
                    logger.info(
                        "Skipping tied pair q=%s persona=%s (scores: %.1f / %.1f)",
                        q["id"],
                        persona.id,
                        chosen_score,
                        rejected_score,
                    )
                    continue

                record = {
                    "source": q["source"],
                    "question_id": q["id"],
                    "query": q["stem"],
                    "persona_id": persona.id,
                    "profile_rendered": profile_rendered,
                    "chosen": chosen_rewrite,
                    "rejected": rejected_rewrite,
                    "chosen_score": chosen_score,
                    "rejected_score": rejected_score,
                }
                out_f.write(json.dumps(record, ensure_ascii=False) + "\n")
                out_f.flush()
                done.add(key)

    store.close()
    logger.info("Preference pair generation complete. Output: %s", output_path)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description="Generate DPO preference pairs for the rewriter.")
    parser.add_argument("--config", required=True, help="Path to phase4 YAML config.")
    args = parser.parse_args()
    with open(args.config, encoding="utf-8") as f:
        config = yaml.safe_load(f)
    run(config)


if __name__ == "__main__":
    main()
